[package]
name = "hackathon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldk-node = { git = "https://github.com/tnull/ldk-node", branch = "2024-02-add-bolt12-support" }
bitcoin = "0.32.0"
